name: CI File Checks
on: pull_request
jobs:
  file_checks:
    runs-on: ubuntu-latest
    steps:
      - name: LFS-warning
        uses: ppremk/lfs-warning@v3.3
        with:
          filesizelimit: 5MB
          exclusionPatterns: |
            **/*.ipynb

      - uses: actions/checkout@v4

      - name: Check for invalid file extensions
        run: |
          python3 <<EOF
          import os

          allowed_extensions = {"md", "py", "yml", "yaml", "txt", "json", "gitignore", "ini", "cfg", "toml", "ipynb"}
          invalid_files = []

          for root, _, files in os.walk("."):
          for file in files:
          ext = file.split(".")[-1] if "." in file else ""
          if ext not in allowed_extensions:
              invalid_files.append(os.path.join(root, file))

          if invalid_files:
          print("Invalid file extensions found:")
          for f in invalid_files:
          print(f)
          exit(1)
          EOF