name: CI File Checks
on: pull_request
jobs:
  file_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for invalid files
        run: |
          python3 .github/workflows/files.py
